name: sync readme

on:
  workflow_dispatch:
  push:
    paths:
      - "README.md"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Sync
      uses: ms-jpq/sync-dockerhub-readme@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ secrets.DOCKERHUB_USERNAME }}/mosdns
        readme: "./README.md"